name: publish

on:
  release:
    types: [published]

env:
  POETRY_VERSION: "1.5.1"
  PYTHON_VERSION: "3.11"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Build package
        run: |
          poetry build
      - name: Publish package on PyPI
        run: |
          poetry publish
      - name: Trigger ReadTheDocs build
        run: |
          echo "Triggering ReadTheDocs build"
  {%- if cookiecutter.codeclimate == 'yes' %}
      - name: Send Velocity deployment
        uses: codeclimate/velocity-deploy-action@master
        with:
          token: {{ '${{ secrets.VELOCITY_DEPLOYMENT_TOKEN }}' }}
          version: {{ '${{ outputs.version }}' }}
          environment: {{ '${{ outputs.environment }}' }}
  {%- endif %}
